
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESISR = 28;
  public static final int PARENTESISL = 27;
  public static final int INTEGER = 17;
  public static final int CONTINUE = 30;
  public static final int identificador = 8;
  public static final int FOR = 32;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int OPMULTI = 21;
  public static final int ELSEIF = 6;
  public static final int IGUAL = 7;
  public static final int EXTSTRING = 29;
  public static final int OR = 23;
  public static final int UNTIL = 39;
  public static final int OPREL = 19;
  public static final int LOOP = 40;
  public static final int NEXT = 34;
  public static final int EXIT = 31;
  public static final int IF = 2;
  public static final int DIM = 10;
  public static final int EOF = 0;
  public static final int CONCATSTRING = 42;
  public static final int RETURN = 41;
  public static final int TRUE = 14;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int BOOLEANTYPE = 13;
  public static final int OPADICION = 20;
  public static final int MODULE = 25;
  public static final int ELSE = 3;
  public static final int TO = 33;
  public static final int WHILE = 37;
  public static final int STRINGTYPE = 18;
  public static final int saltoLinea = 9;
  public static final int THEN = 5;
  public static final int STRUCTURE = 36;
  public static final int END = 4;
  public static final int STRING = 43;
  public static final int FALSE = 15;
  public static final int AS = 12;
  public static final int INTEGERTYPE = 16;
  public static final int SUB = 26;
  public static final int DO = 38;
  public static final int STEP = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "END",
  "THEN",
  "ELSEIF",
  "IGUAL",
  "identificador",
  "saltoLinea",
  "DIM",
  "COMA",
  "AS",
  "BOOLEANTYPE",
  "TRUE",
  "FALSE",
  "INTEGERTYPE",
  "INTEGER",
  "STRINGTYPE",
  "OPREL",
  "OPADICION",
  "OPMULTI",
  "AND",
  "OR",
  "NOT",
  "MODULE",
  "SUB",
  "PARENTESISL",
  "PARENTESISR",
  "EXTSTRING",
  "CONTINUE",
  "EXIT",
  "FOR",
  "TO",
  "NEXT",
  "STEP",
  "STRUCTURE",
  "WHILE",
  "DO",
  "UNTIL",
  "LOOP",
  "RETURN",
  "CONCATSTRING",
  "STRING"
  };
}

